### PR TITLE
Add support for <long> nodes

### PR DESCRIPTION
**Pull request by cmandlbaur**
Add support for the `UseLong` flag to optionally use `<long>` nodes instead of `<i8>` nodes.

Added tests where it seemed to make sense.

Fixed a couple of typos in the README

### CODE REVIEW

**Comment by cmandlbaur** [comment]
@LordVeovis it would be great if this could be included.

It's not really per the xmlrpc spec, but then neither was the `i8` node.

It looks like the build failed to sign because of a login issue.

**Comment by LordVeovis** [comment]
Hey,

I saw your email, I am sorry for not responding here. Currently I do not have Internet at home so... I am not checking here very often as I do not use github at work.
On the paper it looks good.
For now, I have fixing CircleCI pieline and upgraded the project to something supported (.netcore3.1 -> .net 8.0) in the dev-circleci branch. So far so good and I hope to run your code with this base this week. If the tests are green, that should be enough.

So next steps:

1. I run the tests locally
2. If green, I merge dev-circleci on master
3. After the fix, merge it.

Please ignore the Codacy issue.

**Comment by cmandlbaur** [comment]
Thank you!

**Comment by LordVeovis** [comment]
1.3.1 released!

**Pull request merged**
