### PR TITLE
Handle deserialisation of <nil/> data type

### PR DESCRIPTION
**Pull request by steveglen**

### CODE REVIEW

**Comment by LordVeovis** [comment]
Hi,

* Do you have a real case use you can share so we can define a unit test?
* Should we also deal with the serialization part?

**Comment by steveglen** [comment]
My use case is NIPAP, most of its calls return <nil /> in their XML for null values.  For example this call:
https://nipap.readthedocs.io/en/v0.29.6/nipap.html#nipap.backend.Nipap.list_vrf

Response XML looks like this:

<array><data>
		<value><struct>
				<member>
					<name>rt</name>
					<value><nil /></value></member>
				<member>
					<name>total_addresses_v6</name>
					<value><string>871509787656907713528983453696</string></value>
				</member>
				<member>
					<name>total_addresses_v4</name>
					<value><string>53276944</string></value>
				</member>
				<member>
					<name>description</name>
					<value><string>The default VRF, typically the Internet.</string></value>
				</member>
				<member>
					<name>free_addresses_v6</name>
					<value><string>866220736661138132752066936832</string></value>
				</member>
				<member>
					<name>used_addresses_v6</name>
					<value><string>5289050995769580776916516864</string></value>
				</member>
				<member>
					<name>used_addresses_v4</name>
					<value><string>13234488</string></value>
				</member>
				<member>
					<name>tags</name>
					<value><array><data>
							</data></array></value>
				</member>
				<member>
					<name>name</name>
					<value><string>default</string></value>
				</member>
				<member>
					<name>num_prefixes_v6</name>
					<value><string>11679</string></value>
				</member>
				<member>
					<name>avps</name>
					<value><struct>
						</struct></value>
				</member>
				<member>
					<name>num_prefixes_v4</name>
					<value><string>36705</string></value>
				</member>
				<member>
					<name>id</name>
					<value><int>0</int></value>
				</member>
				<member>
					<name>free_addresses_v4</name>
					<value><string>40042456</string></value>
				</member>
			</struct></value>
	</data></array>

Please let me know if you need more info to reproduce

**Comment by steveglen** [comment]
Also it looks like another of the pull requests you have deals with the serialisation?

I came from the latest version of CookComputing.XmlRpc (not the stable version) over to this codebase, in order to work with .net core, but this was a notable regression for me (it worked with the CookComputing codebase).

**Comment by LordVeovis** [comment]
> Also it looks like another of the pull requests you have deals with the serialisation?
> 
> I came from the latest version of CookComputing.XmlRpc (not the stable version) over to this codebase, in order to work with .net core, but this was a notable regression for me (it worked with the CookComputing codebase).

yeah, I'm sorry to read that. I really thought the stability was better than picking up on the beta version when I did convert the Cook's library into .netcore.
Yes #11 is about serialization, which is good as complementary to this one.
I think #13 should be ready this week with a simple unit test.

I'm also making use of this PR to configure circle ci on this project to auto-run the existing tests.

**Pull request merged**
